services:
  - type: web
    name: nlp-backend-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
    healthCheckPath: /api/health
    plan: free

  - type: web
    name: nlp-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
